### ISSUE TITLE
complete exymple

### ISSUE THREAD

**Issue by cforce** [jmnarloch/feign-vnderror-spring-cloud-starter#1]
Would you add an real world example how this be used on the server side and client side if having content type application/json for the 200 ok case?
Is there a way where i could use Feign Error Decoder so wrap the VND expcetion propagation inside Feign, so it would throw the original exception (beeing wrapped on server side) on client side again?
The Feign Error  Decoder shall make use of the same mapping and Codes as the server uses them.
Please show an example How can i make use of the error/exception propagation in a case where using Feign microservice 1 is calling microservice 2 is calling microservice 3  throwing the excepion MyException back to microservice 2 back microservice 1 where MyException raises in Java Code.

**Comment by jmnarloch** [comment]
I afraid that don't understand entirely the first sentence. The vnd errors are only used to have a unified error representation, you don't use them in case that your response have succeeded, also the case your referring to is trivial since, when you add this extension to classpath of your Spring Cloud/Boot application you only need to register @ExceptionHandler for VndErrorException and create instance of Spring HATEOAS VndErrors once again to "propagate" the error information.

As described this extension is going only to decode application/vnd.error+json content types and map does into VndErrorException. It's up to you how you are going map your buisness logic exceptions into status codes etc.

**Comment by cforce** [comment]
Ok, i got more clear now. On the REST API method i can use application/json, but the @ExceptionHandler will set the content type to application/vnd.error+json in exception case, so the client can detect it and throw an VndErrorException  on the client side. 
If wouldn't catch the VndErrorException , could i us ethe  @ExceptionHandler on client side to copy that VndErrorException  into a new new VndErrors() that is propagated one level up to the next callee?

I am afraid i will get a lot of unwished auto config if include HATEOAS dep in my spring cloud app, although i don't really want HATEOAS features in api's generally. The standard vnd struct (HATEOAS compatible) would be acceptable however, only here and nowhere else.

**Comment by jmnarloch** [comment]
> If wouldn't catch the VndErrorException , could i us ethe @ExceptionHandler on client side to copy that VndErrorException into a new new VndErrors() that is propagated one level up to the next callee?

Exactly this is what you need to do.

Well, the reason why the VndErrors has been defined in Spring HATEOAS is that this is kind of metadata that describes the error state and main benefit of it is that it has a unified representation. 

Though except for some feature in Spring Boot 1.3 that enables and registers a customized Jackson mapper there is no real out of the box support for HATEOAS links and you still need to manually register them in the application. Also you can always exclude the specific auto configured classes through @SpringBootApplication(exclude)

**Comment by cforce** [comment]
tx fo help. Waiting for new entries in your blog. Its a pleasure to read them.
